language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-add draft ./
  - asdf list-all draft
  - asdf plugin-test draft ./ 'draft --version'
os:
  - linux
  - osx
